services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: app
      MYSQL_PASSWORD: app123
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: app
      DB_PASSWORD: app123
      DB_NAME: devops
      CORS_ORIGIN: http://localhost:5173,http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:3000
        VITE_APP_NAME: DevOps Mini Project
    ports:
      - "18080:80"
    depends_on:
      - backend

volumes:
  db_data:
